# Generated by Django 2.2 on 2020-01-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('visited', models.BooleanField(default=False)),
            ],
        ),
    ]
