# Generated by Django 2.2 on 2020-01-30 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_auto_20200129_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='pic',
            field=models.ImageField(upload_to='pictures'),
        ),
        migrations.CreateModel(
            name='CandidatePics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='candidates')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
