# Generated by Django 2.2 on 2020-01-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200130_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepics',
            name='images',
            field=models.FileField(upload_to='candidates'),
        ),
    ]
