# Generated by Django 2.2 on 2020-01-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200130_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='pic',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
    ]
